# Generated by Django 4.2.19 on 2025-04-23 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_job_jobapplication'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='discord_channel',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='discord_server',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
