# Generated by Django 5.1.6 on 2025-03-22 00:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_post'),
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('bio', models.CharField(max_length=800)),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='profile_image/')),
                ('created_at', models.DateField(auto_now_add=True)),
                ('members', models.ManyToManyField(blank=True, related_name='joined_organizations', to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_organizations', to=settings.AUTH_USER_MODEL)),
                ('pending_requests', models.ManyToManyField(blank=True, related_name='organization_requests', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='post',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='organization_posts', to='base.organization'),
        ),
    ]
