# Generated by Django 5.1.7 on 2025-03-23 01:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_organization_post_organization'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='organization',
        ),
        migrations.CreateModel(
            name='orgPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=800)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('likes', models.ManyToManyField(blank=True, related_name='org_post_likes', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='organization_posts', to='base.organization')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organization_posts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
